name: Backend CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend_ci_pipeline:
    runs-on: ubuntu-latest

    steps:
      # 1. Code Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Lint
      - name: Lint code
        run: npm run lint

      # 5. Run tests with env vars
      - name: Run tests
        run: npm test
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      # 6. Build Docker image
      - name: Build Docker image
        run: docker build -t ai-snippet-service-backend .
